/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package plugin;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static plugin.Constants.TASK_NAME;
import java.io.IOException;
import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * A simple unit test for the 'plugin.greeting' plugin.
 */
class GradlePluginNoSrcDepsPluginTest {


    private Project project;

    @BeforeEach
    public void init() throws IOException {
        project = createProjectWithPlugin();
    }

    @Test
    void pluginRegistersATask() {
        assertNotNull(project.getTasks().findByName(TASK_NAME));
    }


    private Project createProjectWithPlugin() {

        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("plugin.echofile");
        return project;
    }

//    private Project createProjectWithSampleBuildFile() throws IOException {
//        File projectDir= new File(randomFilename()).getAbsoluteFile();
//        Files.createDirectories(Path.of(projectDir.getAbsolutePath()));
//        writeString(createEmptyBuildGradleFile(projectDir), stringFromResources(Path.of(SAMPLE_GRADLE_FILE)));
//        writeString(createEmptySettingsGradeFile(projectDir), stringFromResources(Path.of(SAMPLE_SETTINGS_FILE)));
//
//        return ProjectBuilder.builder().withProjectDir(projectDir).build();
//    }
//
//    private File createEmptySettingsGradeFile(File projectDir) {
//        return new File(projectDir, "settings.gradle");
//    }
//
//    private File createEmptyBuildGradleFile(File projectDir) {
//        return new File(projectDir, "build.gradle");
//    }
//
//    private String randomFilename() {
//        return "randomFile"+new Random().nextInt(10_000);
//    }
//
//    private void writeString(File file, String string) throws IOException {
//        try (Writer writer = new FileWriter(file)) {
//            writer.write(string);
//        }
//    }
}
