/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package plugin;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static plugin.Constants.TASK_NAME;
import java.io.IOException;
import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * A simple unit test for the 'plugin.greeting' plugin.
 */
class GradlePluginNoSrcDepsPluginTest {


    private Project project;

    @BeforeEach
    public void init() throws IOException {
        project = createProjectWithPlugin();
    }

    @Test
    void pluginRegistersATask() {
        assertNotNull(project.getTasks().findByName(TASK_NAME));
    }


    private Project createProjectWithPlugin() {
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("plugin.echofileplugin");
        return project;
    }


}
