/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package plugin;

import static plugin.Constants.TASK_NAME;
import org.gradle.api.Plugin;
import org.gradle.api.Project;


public class GradlePluginNoSrcDepsPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().register(TASK_NAME, EchoFileTask.class);
    }
}
